version: '3'

services:

    app:
        depends_on:
            - db
        build:
            dockerfile: ./webapi/Dockerfile
        ports:
            - "8080:8080"
        expose:
            - "8080"
        tty: true
        volumes:
            - ./webapi:/go/src/webapi
        environment:
            - DSN=${DSN}
            - ATLAS_DSN=${ATLAS_DSN}
            - DB_NAME=${DB_NAME}
            - DB_USER=${DB_USER}
            - DB_PASS=${DB_PASS}
            - DB_PORT=${DB_PORT}
            - DB_ROOT_PASS=${DB_ROOT_PASS}
            - DB_HOST=${DB_HOST}
            - TEST_DB_NAME=${TEST_DB_NAME}
            - TEST_DB_USER=${TEST_DB_USER}
            - TEST_DB_PASS=${TEST_DB_PASS}
            - TEST_DB_PORT=${TEST_DB_PORT}
            - TEST_DB_HOST=${TEST_DB_HOST}
        container_name: webapi

    db:
        image: mysql:8.0
        volumes:
          - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
        environment:
          - MYSQL_DATABASE=${DB_NAME}
          - MYSQL_USER=${DB_USER}
          - MYSQL_PASSWORD=${DB_PASS}
          - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
          - MYSQL_HOST=${DB_HOST}
          - TZ=${TZ}
        ports:
          - 3306:3306
        container_name: mysql
