swagger: "2.0"
info:
    title: Students API
    description: API for student information management
    version: ""
host: 0.0.0.0:8080
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /students:
        get:
            tags:
                - students
            summary: get_students students
            description: 学籍番号で昇順にソートされた全ての学生を取得する。
            operationId: students#get_students
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/StudentsGetStudentsResponseBody'
                "500":
                    description: Internal Server Error response.
                    schema:
                        $ref: '#/definitions/StudentsGetStudentsInternalErrorResponseBody'
                        required:
                            - name
                            - message
            schemes:
                - http
        post:
            tags:
                - students
            summary: create_student students
            description: 学生を登録する。
            operationId: students#create_student
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/StudentsCreateStudentResponseBody'
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/StudentsCreateStudentBadRequestResponseBody'
                        required:
                            - name
                            - message
                "500":
                    description: Internal Server Error response.
                    schema:
                        $ref: '#/definitions/StudentsCreateStudentInternalErrorResponseBody'
                        required:
                            - name
                            - message
            schemes:
                - http
    /students/{student_number}:
        get:
            tags:
                - students
            summary: get_student students
            description: 学籍番号から学生を取得する。
            operationId: students#get_student
            parameters:
                - name: student_number
                  in: path
                  description: Student's unique number
                  required: true
                  type: integer
                  format: int64
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/StudentsGetStudentResponseBody'
                "404":
                    description: Not Found response.
                    schema:
                        $ref: '#/definitions/StudentsGetStudentNotFoundResponseBody'
                        required:
                            - name
                            - message
                "500":
                    description: Internal Server Error response.
                    schema:
                        $ref: '#/definitions/StudentsGetStudentInternalErrorResponseBody'
                        required:
                            - name
                            - message
            schemes:
                - http
definitions:
    StudentResponseBody:
        title: 'Mediatype identifier: application/vnd.student+json; view=default'
        type: object
        properties:
            address:
                type: string
                description: 学生の住所
                example: 名古屋市中区三の丸三丁目1番2号
            date_of_birth:
                type: string
                description: 学生の生年月日 (RFC3339)
                example: "2022-04-01T13:30:00+09:00"
                format: date-time
            expiration_date:
                type: string
                description: 学生証の有効期間 (RFC3339)
                example: "2027-03-31T00:00:00+09:00"
                format: date-time
            id:
                type: integer
                description: 学生を一意に表す ID
                example: 1
                format: int64
            name:
                type: string
                description: 学生の氏名
                example: 鈴木太郎
            ruby:
                type: string
                description: 学生の氏名のフリガナ
                example: スズキタロウ
            student_number:
                type: integer
                description: 学生の学籍番号
                example: 12345
                format: int64
        description: One student (default view)
        example:
            address: 名古屋市中区三の丸三丁目1番2号
            date_of_birth: "2022-04-01T13:30:00+09:00"
            expiration_date: "2027-03-31T00:00:00+09:00"
            id: 1
            name: 鈴木太郎
            ruby: スズキタロウ
            student_number: 12345
        required:
            - id
            - name
            - ruby
            - student_number
            - date_of_birth
            - address
            - expiration_date
    StudentsCreateStudentBadRequestResponseBody:
        title: StudentsCreateStudentBadRequestResponseBody
        type: object
        properties:
            message:
                type: string
                description: Message of error
                example: This is an error message.
            name:
                type: string
                description: Name of error
                example: internal_error
        example:
            message: This is an error message.
            name: internal_error
        required:
            - name
            - message
    StudentsCreateStudentInternalErrorResponseBody:
        title: StudentsCreateStudentInternalErrorResponseBody
        type: object
        properties:
            message:
                type: string
                description: Message of error
                example: This is an error message.
            name:
                type: string
                description: Name of error
                example: internal_error
        example:
            message: This is an error message.
            name: internal_error
        required:
            - name
            - message
    StudentsCreateStudentResponseBody:
        title: 'Mediatype identifier: application/vnd.student+json; view=default'
        type: object
        properties:
            address:
                type: string
                description: 学生の住所
                example: 名古屋市中区三の丸三丁目1番2号
            date_of_birth:
                type: string
                description: 学生の生年月日 (RFC3339)
                example: "2022-04-01T13:30:00+09:00"
                format: date-time
            expiration_date:
                type: string
                description: 学生証の有効期間 (RFC3339)
                example: "2027-03-31T00:00:00+09:00"
                format: date-time
            id:
                type: integer
                description: 学生を一意に表す ID
                example: 1
                format: int64
            name:
                type: string
                description: 学生の氏名
                example: 鈴木太郎
            ruby:
                type: string
                description: 学生の氏名のフリガナ
                example: スズキタロウ
            student_number:
                type: integer
                description: 学生の学籍番号
                example: 12345
                format: int64
        description: create_student_response_body result type (default view)
        example:
            address: 名古屋市中区三の丸三丁目1番2号
            date_of_birth: "2022-04-01T13:30:00+09:00"
            expiration_date: "2027-03-31T00:00:00+09:00"
            id: 1
            name: 鈴木太郎
            ruby: スズキタロウ
            student_number: 12345
        required:
            - id
            - name
            - ruby
            - student_number
            - date_of_birth
            - address
            - expiration_date
    StudentsGetStudentInternalErrorResponseBody:
        title: StudentsGetStudentInternalErrorResponseBody
        type: object
        properties:
            message:
                type: string
                description: Message of error
                example: This is an error message.
            name:
                type: string
                description: Name of error
                example: internal_error
        example:
            message: This is an error message.
            name: internal_error
        required:
            - name
            - message
    StudentsGetStudentNotFoundResponseBody:
        title: StudentsGetStudentNotFoundResponseBody
        type: object
        properties:
            message:
                type: string
                description: Message of error
                example: This is an error message.
            name:
                type: string
                description: Name of error
                example: internal_error
        example:
            message: This is an error message.
            name: internal_error
        required:
            - name
            - message
    StudentsGetStudentResponseBody:
        title: 'Mediatype identifier: application/vnd.student+json; view=default'
        type: object
        properties:
            address:
                type: string
                description: 学生の住所
                example: 名古屋市中区三の丸三丁目1番2号
            date_of_birth:
                type: string
                description: 学生の生年月日 (RFC3339)
                example: "2022-04-01T13:30:00+09:00"
                format: date-time
            expiration_date:
                type: string
                description: 学生証の有効期間 (RFC3339)
                example: "2027-03-31T00:00:00+09:00"
                format: date-time
            id:
                type: integer
                description: 学生を一意に表す ID
                example: 1
                format: int64
            name:
                type: string
                description: 学生の氏名
                example: 鈴木太郎
            ruby:
                type: string
                description: 学生の氏名のフリガナ
                example: スズキタロウ
            student_number:
                type: integer
                description: 学生の学籍番号
                example: 12345
                format: int64
        description: get_student_response_body result type (default view)
        example:
            address: 名古屋市中区三の丸三丁目1番2号
            date_of_birth: "2022-04-01T13:30:00+09:00"
            expiration_date: "2027-03-31T00:00:00+09:00"
            id: 1
            name: 鈴木太郎
            ruby: スズキタロウ
            student_number: 12345
        required:
            - id
            - name
            - ruby
            - student_number
            - date_of_birth
            - address
            - expiration_date
    StudentsGetStudentsInternalErrorResponseBody:
        title: StudentsGetStudentsInternalErrorResponseBody
        type: object
        properties:
            message:
                type: string
                description: Message of error
                example: This is an error message.
            name:
                type: string
                description: Name of error
                example: internal_error
        example:
            message: This is an error message.
            name: internal_error
        required:
            - name
            - message
    StudentsGetStudentsResponseBody:
        title: 'Mediatype identifier: application/vnd.students+json; view=default'
        type: object
        properties:
            students:
                type: array
                items:
                    $ref: '#/definitions/StudentResponseBody'
                example:
                    - address: 名古屋市中区三の丸三丁目1番2号
                      date_of_birth: "2022-04-01T13:30:00+09:00"
                      expiration_date: "2027-03-31T00:00:00+09:00"
                      id: 1
                      name: 鈴木太郎
                      ruby: スズキタロウ
                      student_number: 12345
                    - address: 名古屋市中区三の丸三丁目1番2号
                      date_of_birth: "2022-04-01T13:30:00+09:00"
                      expiration_date: "2027-03-31T00:00:00+09:00"
                      id: 1
                      name: 鈴木太郎
                      ruby: スズキタロウ
                      student_number: 12345
                    - address: 名古屋市中区三の丸三丁目1番2号
                      date_of_birth: "2022-04-01T13:30:00+09:00"
                      expiration_date: "2027-03-31T00:00:00+09:00"
                      id: 1
                      name: 鈴木太郎
                      ruby: スズキタロウ
                      student_number: 12345
                    - address: 名古屋市中区三の丸三丁目1番2号
                      date_of_birth: "2022-04-01T13:30:00+09:00"
                      expiration_date: "2027-03-31T00:00:00+09:00"
                      id: 1
                      name: 鈴木太郎
                      ruby: スズキタロウ
                      student_number: 12345
        description: get_students_response_body result type (default view)
        example:
            students:
                - address: 名古屋市中区三の丸三丁目1番2号
                  date_of_birth: "2022-04-01T13:30:00+09:00"
                  expiration_date: "2027-03-31T00:00:00+09:00"
                  id: 1
                  name: 鈴木太郎
                  ruby: スズキタロウ
                  student_number: 12345
                - address: 名古屋市中区三の丸三丁目1番2号
                  date_of_birth: "2022-04-01T13:30:00+09:00"
                  expiration_date: "2027-03-31T00:00:00+09:00"
                  id: 1
                  name: 鈴木太郎
                  ruby: スズキタロウ
                  student_number: 12345
        required:
            - students
