// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package datastore

import (
	"time"
)

type Student struct {
	ID             uint64
	Name           string
	Ruby           string
	StudentNumber  uint32
	DateOfBirth    time.Time
	Address        string
	ExpirationDate time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
}
